export const GET_HOME_INFO = "GET_HOME_INFO"
export const SET_HOME_INFO = "SET_HOME_INFO"
export const ADD_HOME_ARTICLE_LIST ='ADD_HOME_ARTICLE_LIST'
export const CHANGE_SCROLL_SHOW ='CHANGE_SCROLL_SHOW'